In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)

[10 20 30 40 50]
<class 'numpy.ndarray'>
(5,)
1


In [3]:
print(arr[0])
print(arr[-1])
print(arr[1:4])

10
50
[20 30 40]


In [4]:
print(arr + 5)
print(arr * 2)
print(arr.mean())
print(arr.sum())
print(arr.max())
print(arr.min())

[15 25 35 45 55]
[ 20  40  60  80 100]
30.0
150
50
10


In [5]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix[0, 0])
print(matrix[:, 1])
print(matrix[0:2, 1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
1
[2 5 8]
[[2 3]
 [5 6]]
